version: "3.9"
services:
  web:
    build: .
    ports:
      - "8083:8080"
    links:
      - "mongo:database"
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    restart: always
    ports:
      - "8084:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: UitDaging

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: UitDaging
      ME_CONFIG_MONGODB_URL: mongodb://root:UitDaging@mongo:8084/

networks:
  servercore:
    driver: bridge
